# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='schedule',
  serialized_pb=_b('\n\ntask.proto\x12\x08schedule\"\x8d\x01\n\x0bTimeSegment\x12\x10\n\x08\x64uration\x18\x01 \x01(\x05\x12\x14\n\tcool_down\x18\x02 \x01(\x05:\x01\x30\x12\x10\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\x05\x12\x17\n\x0f\x65\x61rliest_starts\x18\x04 \x03(\x05\x12\x15\n\rlatest_starts\x18\x05 \x03(\x05\x12\x14\n\x08priority\x18\x06 \x01(\x05:\x02\x31\x30\"[\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x13\n\x0bpre_req_ids\x18\x03 \x03(\t\x12#\n\x04time\x18\x05 \x01(\x0b\x32\x15.schedule.TimeSegment\"2\n\x08Schedule\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\"y\n\x05Tasks\x12\x1d\n\x05tasks\x18\x01 \x03(\x0b\x32\x0e.schedule.Task\x12\x1c\n\x11global_start_time\x18\x02 \x01(\x05:\x01\x30\x12\x14\n\trest_time\x18\x03 \x01(\x05:\x01\x30\x12\x1d\n\rmax_heap_size\x18\x04 \x01(\x05:\x06\x35\x30\x30\x30\x30\x30\"\xee\x01\n\tSchedules\x12%\n\tschedules\x18\x01 \x03(\x0b\x32\x12.schedule.Schedule\x12\x14\n\x0csearch_steps\x18\x02 \x01(\x05\x12/\n\x06status\x18\x03 \x01(\x0e\x32\x1f.schedule.Schedules.FinalStatus\x12\x18\n\x10incomplete_tasks\x18\x04 \x03(\t\x12\x16\n\x0etotal_duration\x18\x05 \x01(\x05\x12\x15\n\rused_duration\x18\x06 \x01(\x05\"*\n\x0b\x46inalStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0e\n\nINCOMPLETE\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SCHEDULES_FINALSTATUS = _descriptor.EnumDescriptor(
  name='FinalStatus',
  full_name='schedule.Schedules.FinalStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCOMPLETE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=633,
  serialized_end=675,
)
_sym_db.RegisterEnumDescriptor(_SCHEDULES_FINALSTATUS)


_TIMESEGMENT = _descriptor.Descriptor(
  name='TimeSegment',
  full_name='schedule.TimeSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='schedule.TimeSegment.duration', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cool_down', full_name='schedule.TimeSegment.cool_down', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deadline', full_name='schedule.TimeSegment.deadline', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='earliest_starts', full_name='schedule.TimeSegment.earliest_starts', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latest_starts', full_name='schedule.TimeSegment.latest_starts', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='schedule.TimeSegment.priority', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=166,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='schedule.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='schedule.Task.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group', full_name='schedule.Task.group', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pre_req_ids', full_name='schedule.Task.pre_req_ids', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='schedule.Task.time', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=259,
)


_SCHEDULE = _descriptor.Descriptor(
  name='Schedule',
  full_name='schedule.Schedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='schedule.Schedule.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='schedule.Schedule.start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='schedule.Schedule.end', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=311,
)


_TASKS = _descriptor.Descriptor(
  name='Tasks',
  full_name='schedule.Tasks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='schedule.Tasks.tasks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='global_start_time', full_name='schedule.Tasks.global_start_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rest_time', full_name='schedule.Tasks.rest_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_heap_size', full_name='schedule.Tasks.max_heap_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=500000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=434,
)


_SCHEDULES = _descriptor.Descriptor(
  name='Schedules',
  full_name='schedule.Schedules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schedules', full_name='schedule.Schedules.schedules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_steps', full_name='schedule.Schedules.search_steps', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='schedule.Schedules.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='incomplete_tasks', full_name='schedule.Schedules.incomplete_tasks', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_duration', full_name='schedule.Schedules.total_duration', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='used_duration', full_name='schedule.Schedules.used_duration', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SCHEDULES_FINALSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=675,
)

_TASK.fields_by_name['time'].message_type = _TIMESEGMENT
_TASKS.fields_by_name['tasks'].message_type = _TASK
_SCHEDULES.fields_by_name['schedules'].message_type = _SCHEDULE
_SCHEDULES.fields_by_name['status'].enum_type = _SCHEDULES_FINALSTATUS
_SCHEDULES_FINALSTATUS.containing_type = _SCHEDULES
DESCRIPTOR.message_types_by_name['TimeSegment'] = _TIMESEGMENT
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Schedule'] = _SCHEDULE
DESCRIPTOR.message_types_by_name['Tasks'] = _TASKS
DESCRIPTOR.message_types_by_name['Schedules'] = _SCHEDULES

TimeSegment = _reflection.GeneratedProtocolMessageType('TimeSegment', (_message.Message,), dict(
  DESCRIPTOR = _TIMESEGMENT,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:schedule.TimeSegment)
  ))
_sym_db.RegisterMessage(TimeSegment)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:schedule.Task)
  ))
_sym_db.RegisterMessage(Task)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULE,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:schedule.Schedule)
  ))
_sym_db.RegisterMessage(Schedule)

Tasks = _reflection.GeneratedProtocolMessageType('Tasks', (_message.Message,), dict(
  DESCRIPTOR = _TASKS,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:schedule.Tasks)
  ))
_sym_db.RegisterMessage(Tasks)

Schedules = _reflection.GeneratedProtocolMessageType('Schedules', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULES,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:schedule.Schedules)
  ))
_sym_db.RegisterMessage(Schedules)


# @@protoc_insertion_point(module_scope)
